services:
  csvserver:
    ports:
      - "9393:9300"
    # image to fetch from docker hub
    image: infracloudio/csvserver:latest

    # Environment variables for startup script
    environment:
      - "CSVSERVER_BORDER=Orange"
    # Mount volume 
    volumes:
      - "./inputFile:/csvserver/inputdata"
  prometheus:
    ports:
      - "9090:9090"
    # image to fetch from docker hub
    image: prom/prometheus:v2.22.0
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"

